# Generated by Django 3.2.9 on 2023-08-16 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='training_skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interested_in_technical_training', models.CharField(choices=[('data science', 'Data Science'), ('MERN', 'MERN Full Stack Developer'), ('MEAN', 'MEAN FULL Stack Developer'), ('Java', 'Java Full Stack Developer'), ('Testing', 'Testing'), ('Networking', 'Networking'), ('Oracle', 'Oracle Certificate'), ('Dot Net ', '.Net Full Stack Developer'), ('UI/UX', 'UI/UX')], max_length=30)),
                ('interested_in_soft_skill_training', models.CharField(choices=[('Communication Skills', 'Communication Skills'), ('LinkedIn', 'Training on LinkedIn'), ('Presentation Skills', 'Presentation Skills'), ('Interview Preparation', 'Interview Preparation'), ('Interpersonal Skills', 'Interpersonal Skills')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='shortlisted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='placement.company_details')),
                ('user', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
